services:

  mysql:
    image: mysql:8.0
    container_name: products-mysql
    environment:
      MYSQL_ROOT_PASSWORD: secretkey
      MYSQL_DATABASE: productsdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  app:
    build: .
    container_name: products-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/productsdb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Kolkata
      SPRING_DATASOURCE_USERNAME: secretdb
      SPRING_DATASOURCE_PASSWORD: secretkey
    depends_on:
      - mysql
    restart: unless-stopped

volumes:
  mysql_data:
